# Generated by Django 2.0.6 on 2018-07-29 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysedimage',
            name='collection',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='analysed_images', to='core.Collection'),
            preserve_default=False,
        ),
    ]
