# Generated by Django 2.0.6 on 2018-07-29 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180729_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Título da Coleção'),
        ),
    ]
