# Generated by Django 2.0.6 on 2018-07-30 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20180729_1922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analysedimage',
            old_name='job_id',
            new_name='recokgnition_job_id',
        ),
    ]
