# Generated by Django 2.0.6 on 2018-07-31 07:10

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20180730_2007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={},
        ),
        migrations.AddField(
            model_name='analysedimage',
            name='google_vision_job_id',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Id job de análise'),
        ),
        migrations.AddField(
            model_name='analysedimage',
            name='google_vision_result',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, verbose_name='AWS Recokgnition'),
        ),
    ]
