# Generated by Django 2.0.6 on 2018-08-02 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20180731_0509'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'verbose_name': 'Coleção', 'verbose_name_plural': 'Coleções'},
        ),
        migrations.AddField(
            model_name='analysedimage',
            name='yolo_image',
            field=models.ImageField(default='', upload_to='yolo/', verbose_name='Output YOLO'),
            preserve_default=False,
        ),
    ]
