# Generated by Django 2.0.6 on 2018-08-02 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20180802_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysedimage',
            name='yolo_job_id',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Yolo Job'),
        ),
        migrations.AlterField(
            model_name='analysedimage',
            name='azure_vision_job_id',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Azure Job'),
        ),
        migrations.AlterField(
            model_name='analysedimage',
            name='google_vision_job_id',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Google Job'),
        ),
    ]
