# Generated by Django 2.0.6 on 2018-08-08 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20180802_0221'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysedimage',
            options={'ordering': ['image'], 'verbose_name': 'Análise de Imagem', 'verbose_name_plural': 'Análise de Imagem'},
        ),
        migrations.AddField(
            model_name='analysedimage',
            name='detectron_image',
            field=models.ImageField(null=True, upload_to='detectron/', verbose_name='Output Detectron'),
        ),
    ]
