# Generated by Django 2.0.6 on 2018-08-15 02:12

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20180814_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysedimage',
            name='clarifai_job_id',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Clarifai Job'),
        ),
        migrations.AddField(
            model_name='analysedimage',
            name='clarifai_result',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, verbose_name='Clarifai'),
        ),
    ]
