# Generated by Django 2.0.6 on 2018-08-20 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20180814_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysedimage',
            name='dense_cap_full_image',
            field=models.ImageField(null=True, upload_to='dense_cap/', verbose_name='Output Dense Cap (all results)'),
        ),
        migrations.AddField(
            model_name='analysedimage',
            name='dense_cap_image',
            field=models.ImageField(null=True, upload_to='dense_cap/', verbose_name='Output Dense Cap (10 results)'),
        ),
        migrations.AddField(
            model_name='analysedimage',
            name='dense_cap_job_id',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Dense Cap Job'),
        ),
    ]
