# Generated by Django 2.0.6 on 2018-10-15 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20180820_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='public',
            field=models.BooleanField(default=True, verbose_name='Coleção Pública'),
        ),
    ]
