# Generated by Django 2.2.2 on 2019-06-06 12:12

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_collection_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysedimage',
            name='azure_vision_result',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='AWS Recokgnition'),
        ),
        migrations.AlterField(
            model_name='analysedimage',
            name='clarifai_result',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='Clarifai'),
        ),
        migrations.AlterField(
            model_name='analysedimage',
            name='deep_ai_result',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='Deep AI'),
        ),
        migrations.AlterField(
            model_name='analysedimage',
            name='google_vision_result',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='AWS Recokgnition'),
        ),
        migrations.AlterField(
            model_name='analysedimage',
            name='ibm_watson_result',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='IBM Watson'),
        ),
        migrations.AlterField(
            model_name='analysedimage',
            name='recokgnition_result',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='AWS Recokgnition'),
        ),
    ]
